// import { Container } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect } from "react";
import { Blog } from "../src/compo/Blogs";
import { useGlobal } from "../src/context/GlobalItemsProvider";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { Container } from "@mui/material";
import { useAuth } from "../src/context/AuthenticationProvider";

export default function Home({ data: { allBlogs } }) {
  let { URL } = useGlobal();
  let { setLogginUserData } = useAuth();

  useEffect(() => {
    setLogginUserData(JSON.parse(localStorage.getItem("user"))?.profile);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ pt: 2 }}>
        <React.Suspense fallback="Loading...">
          {/* make dynamic */}

          {allBlogs &&
            allBlogs?.map((blog, index) => (
              <Blog blog={blog} key={index} index={index} />
            ))}
        </React.Suspense>
        <footer className={styles.footer}>
          All Rights reserved by Dev Blog
        </footer>
      </Container>
    </div>
  );
}

export async function getServerSideProps() {
  // export async function getStaticProps() {
  const res = await fetch(
    `https://mernblog.azurewebsites.net/api/v1/blogs/?page=1`
  );

  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
